---
title: "Analyse croisée : pauvreté et îlots de chaleur à Gennevilliers"
author: "Headlab92"
date: "2026"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---

# Analyse croisée : pauvreté et îlots de chaleur

## Chargement des librairies

```{r libraries, message=FALSE, warning=FALSE}
library(sf)
library(mapsf)
library(happign)
library(dplyr)
```

## Chargement des données de pauvreté

```{r pauvrete, message=FALSE, warning=FALSE}
car <- st_read("carreaux_200m_met.gpkg", quiet = TRUE)
carGEN <- car[car$lcog_geo == "92036",]
carGEN <- carGEN[, c("ind_snv", "geom")]
```

## Récupération des données d'occupation du sol

```{r occupation, message=FALSE, warning=FALSE}
gennevilliers_commune <- get_wfs(
  x = NULL,
  layer = "LIMITES_ADMINISTRATIVES_EXPRESS.LATEST:commune",
  query = "code_insee = '92036'"
)

vegetation <- get_wfs(
  x = gennevilliers_commune,
  layer = "BDTOPO_V3:zone_de_vegetation",
  predicate = intersects()
)
```

## Calcul de la végétation par carreau

```{r calcul, message=FALSE, warning=FALSE}
# Reprojection dans le même CRS
vegetation <- st_transform(vegetation, st_crs(carGEN))

# Calcul de la surface de végétation qui intersecte chaque carreau
inter <- st_intersection(carGEN, vegetation)
inter$surf_veg <- as.numeric(st_area(inter))

# Agrégation par carreau
veg_par_carreau <- inter %>%
  st_drop_geometry() %>%
  group_by(ind_snv) %>%
  summarise(surf_veg_totale = sum(surf_veg, na.rm = TRUE))

# Jointure avec les carreaux
carGEN <- carGEN %>%
  left_join(veg_par_carreau, by = "ind_snv")

# Remplacer les NA par 0 (carreaux sans végétation)
carGEN$surf_veg_totale[is.na(carGEN$surf_veg_totale)] <- 0
```

## Carte comparative

```{r carte, message=FALSE, warning=FALSE}
par(mfrow = c(1, 2))

# Carte pauvreté
mf_map(carGEN,
       type = "choro",
       var = "ind_snv",
       breaks = "quantile",
       nbreaks = 5,
       pal = "Reds",
       border = NA,
       leg_title = "Niveau de vie (€)")

# Carte végétation
mf_map(carGEN,
       type = "choro",
       var = "surf_veg_totale",
       breaks = "quantile",
       nbreaks = 5,
       pal = "Greens",
       border = NA,
       leg_title = "Surface végétation (m²)")

par(mfrow = c(1, 1))
```

## Corrélation entre pauvreté et végétation

```{r correlation, message=FALSE, warning=FALSE}
# Graphique de corrélation
plot(carGEN$ind_snv, carGEN$surf_veg_totale,
     xlab = "Niveau de vie médian (€)",
     ylab = "Surface de végétation (m²)",
     main = "Lien entre niveau de vie et végétation",
     col = "steelblue",
     pch = 16)

abline(lm(surf_veg_totale ~ ind_snv, data = carGEN), col = "red")

# Coefficient de corrélation
cor.test(carGEN$ind_snv, carGEN$surf_veg_totale)
```