---
title: "Cartographie des îlots de chaleur à Gennevilliers"
author: "Heatlab92"
date: "2026"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---

# Cartographie des îlots de chaleur à Gennevilliers

## Chargement des librairies

```{r libraries, message=FALSE, warning=FALSE}
library(sf)
library(mapsf)
library(happign)
library(dplyr)
```

## Récupération du contour de Gennevilliers

```{r contour, message=FALSE, warning=FALSE}
gennevilliers_commune <- get_wfs(
  x = NULL,
  layer = "LIMITES_ADMINISTRATIVES_EXPRESS.LATEST:commune",
  query = "code_insee = '92036'"
)
plot(gennevilliers_commune$geometry)
```

## Récupération des zones de végétation

```{r vegetation, message=FALSE, warning=FALSE}
vegetation <- get_wfs(
  x = gennevilliers_commune,
  layer = "BDTOPO_V3:zone_de_vegetation",
  predicate = intersects()
)
plot(vegetation$geometry)
```

## Récupération des zones d'habitation

```{r habitation, message=FALSE, warning=FALSE}
habitation <- get_wfs(
  x = gennevilliers_commune,
  layer = "BDTOPO_V3:zone_d_habitation",
  predicate = intersects()
)
plot(habitation$geometry)
```

## Carte des îlots de chaleur potentiels

```{r carte, message=FALSE, warning=FALSE}
# Carte de base avec le contour de Gennevilliers
mf_map(gennevilliers_commune, 
       type = "base", 
       col = "grey90", 
       border = "black")

# Zones d'habitation en rouge (zones chaudes)
mf_map(habitation, 
       type = "base", 
       col = "firebrick", 
       border = NA, 
       add = TRUE)

# Végétation en vert (zones fraîches)
mf_map(vegetation, 
       type = "base", 
       col = "darkgreen", 
       border = NA, 
       add = TRUE)

# Légende
mf_legend(type = "typo",
          val = c("Zones d'habitation (chaleur)", "Végétation (fraîcheur)"),
          pal = c("firebrick", "darkgreen"),
          title = "Occupation du sol")
```