---
title: "Cartographie de la pauvreté à Gennevilliers"
author: "Heatlab92"
date: "2026"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    self_contained: true
---

# Cartographie de la pauvreté à Gennevilliers

## Chargement des librairies

```{r libraries, message=FALSE, warning=FALSE}
library(sf)
library(mapsf)
library(dplyr)
```

## Chargement et filtrage des données

```{r chargement}
# Chargement des carreaux 200m
car <- st_read("carreaux_200m_met.gpkg", quiet=T)

# Filtrage sur Gennevilliers (code INSEE 92036)
carGEN <- car[car$lcog_geo == "92036",]

plot(carGEN$geom)
```

## Distribution des ménages pauvres

```{r histogramme}
hist(carGEN$ind_snv, 
     main = "Distribution du niveau de vie médian",
     xlab = "Niveau de vie médian (€)",
     col = "steelblue")

summary(carGEN$ind_snv)
```

## Carte du niveau de vie médian

```{r carte}
mf_map(carGEN, 
       type = "choro",
       var = "ind_snv",
       breaks = "quantile",
       nbreaks = 5,
       pal = "Reds",
       border = NA,
       leg_title = "Niveau de vie médian (€)")

```
